version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=biotrack
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
    volumes:
      - postgres_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d biotrack"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev:
